### ISSUE TITLE
Crash when converting to keyframes

### ISSUE THREAD

**Issue by LuukvanEck** [z64a/star-rod#5]
1. Open star rod sprite editor
2. Go to WUA
3. Open Fatomb https://github.com/abys-games/wish-upon-abyss/tree/94-fat-omb/assets/wua/sprite/npc/FatOmb
4. Try to convert to keyframes

```
Exception in thread "main" app.StarRodException: Cannot invoke "game.sprite.editor.animators.KeyframeAnimator$Keyframe.setImage(java.util.Queue)" because "curKf" is null
        at game.sprite.editor.animators.KeyframeAnimator.generate(KeyframeAnimator.java:247)
        at game.sprite.SpriteComponent.convertToKeyframes(SpriteComponent.java:397)
        at game.sprite.Sprite.convertToKeyframes(Sprite.java:520)
        at game.sprite.editor.SpriteEditor.lambda$20(SpriteEditor.java:1060)
        at game.map.editor.common.BaseEditor.lambda$3(BaseEditor.java:232)
        at org.lwjgl.opengl.awt.AWTGLCanvas.runInContext(AWTGLCanvas.java:94)
        at game.map.editor.GLEditor.runInContext(GLEditor.java:22)
        at game.map.editor.common.BaseEditor.launch(BaseEditor.java:230)
        at game.sprite.editor.SpriteEditor.main(SpriteEditor.java:214)
```

**Comment by LuukvanEck** [comment]
I wanted to add that whenever I try to duplicate an animation, it just creates an empty animation. I have no idea what is going wrong with this specific enemy.
```
		<Animation name="IdleH (copy)">
			<Component name="torso" xyz="11,7,0">
			</Component>
			<Component name="fuse" xyz="11,89,-2">
			</Component>
			<Component name="frontfoot" xyz="15,-6,1">
			</Component>
			<Component name="backfoot" xyz="-23,-6,-2">
			</Component>
			<Component name="hat" xyz="-1,54,0">
			</Component>
			<Component name="eyes" xyz="-11,35,0">
			</Component>
			<Component name="parent_t_f" xyz="0,0,0">
			</Component>
		</Animation>
```
